//Random
export const EMAIL_CONFIG = Object.freeze({
    LAST_MONTH_DISABLING_WARNING_EMAIL: "MC001",
    UPDATE_SYSTEM_REMINDER_EMAIL: "MC002",
})

export const EMAIL_CONFIG_CODES = Object.freeze([EMAIL_CONFIG.LAST_MONTH_DISABLING_WARNING_EMAIL, EMAIL_CONFIG.UPDATE_SYSTEM_REMINDER_EMAIL])
